[package]
edition = "2021"
name = "matching-engine"
version = "0.1.0"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.6", features = ["derive", "env"] }
etherparse = "0.15.0"
mio = { version = "0.8.11", features = ["net"] }
protocol = { path = "../protocol" }
slab = "0.4.9"
