[package]
edition = "2021"
name = "matching-engine"
version = "0.1.0"

[dependencies]
anyhow = "1.0.86"
bbqueue = "0.5.1"
clap = { version = "4.5.6", features = ["derive", "env"] }
etherparse = "0.15.0"
glommio = "0.9.0"
protocol = { path = "../protocol" }
slab = "0.4.9"
