[package]
edition = "2021"
name = "matching-engine"
version = "0.1.0"

[dependencies]
anyhow = "1.0.86"
bbqueue = "0.5.1"
clap = { version = "4.5.6", features = ["derive", "env"] }
etherparse = "0.15.0"
monoio = "0.2.3"
protocol = { path = "../protocol" }
