apiVersion: v1
kind: Service
metadata:
  name: exchange-headless
  namespace: exchange
  labels:
    app: exchange
spec:
  clusterIP: None
  ports:
    - name: api
      port: 8080
      protocol: TCP
    - name: litefs
      port: 20202
      protocol: TCP
  selector: 
    app: exchange
    component: api
---
apiVersion: v1
kind: Service
metadata:
  name: exchange
  namespace: exchange
  labels:
    app: exchange
spec:
  ports:
    - name: api
      port: 8080
      protocol: TCP
  selector: 
    app: exchange
    component: api
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: exchange
  namespace: exchange
  labels:
    app: exchange
    component: api
spec:
  serviceName: exchange-headless
  replicas: 3
  selector:
    matchLabels:
      app: exchange
      component: api
  template:
    metadata:
      labels:
        app: exchange
        component: api
    spec:
      containers:
      - name: exchange
        image: suremarc/mkt-sim-exchange:latest
        securityContext:
          privileged: true
        command: 
        - litefs
        - mount
        - -config
        - /etc/config/litefs.yml
        ports:
        - name: api
          containerPort: 8080
        - name: litefs
          containerPort: 20202
        readinessProbe:
          httpGet:
            path: /swagger
            port: 8080
        livenessProbe:
          httpGet:
            path: /swagger
            port: 8080
          failureThreshold: 1
        env:
        - name: ROCKET_CONFIG
          value: /etc/config/Rocket.toml
        - name: ROCKET_ADMIN.EMAIL
          valueFrom:
            secretKeyRef:
              name: admin
              key: email
        - name: ROCKET_ADMIN.PASSWORD
          valueFrom:
            secretKeyRef:
              name: admin
              key: password
        - name: ROCKET_DATABASES.ORDERS.URL
          valueFrom:
            secretKeyRef:
              name: redis
              key: uri
        - name: ROCKET_DATABASES.META.URL
          value: /litefs/my.db
        - name: ROCKET_DATABASES.ACCOUNTING.URL
          value: tigerbeetle-headless.tigerbeetle:4242
        # todo: figure out how to link tigerbeetle
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - name: config
          mountPath: /etc/config
        - name: litefs
          mountPath: /var/lib/litefs
      volumes:
      - name: config
        configMap:
          name: api-config
  volumeClaimTemplates:
  - metadata:
      name: litefs
      namespace: exchange
    spec:
      accessModes: 
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
