apiVersion: v1
kind: Service
metadata:
  name: exchange
  namespace: exchange
  labels:
    app: exchange
spec:
  ports:
    - name: api
      port: 8000
      protocol: TCP
  selector: 
    app: exchange
    component: api
---
apiVersion: v1
kind: Service
metadata:
  name: exchange-lb
  namespace: exchange
  labels:
    app: exchange
  annotations:
    # No TLS port annotation needed since 443 is assumed for HTTPS when another TLS option annotation is given.
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "8ff40e5d-ae73-4c5e-9e57-36d8d063d05d"
spec:
  type: LoadBalancer
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8000
  selector:
    app: exchange
    component: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchange
  namespace: exchange
  labels:
    app: exchange
    component: api
spec:
  selector:
    matchLabels:
      app: exchange
      component: api
  template:
    metadata:
      labels:
        app: exchange
        component: api
    spec:
      containers:
      - name: exchange
        image: suremarc/mkt-sim-exchange:latest
        ports:
        - name: api
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /swagger/index.html
            port: 8000
        livenessProbe:
          httpGet:
            path: /swagger/index.html
            port: 8000
          failureThreshold: 1
        env:
        - name: ROCKET_CONFIG
          value: /etc/config/Rocket.toml
        - name: ROCKET_JWT.SECRET
          valueFrom:
            secretKeyRef:
              name: jwt
              key: key
        - name: ROCKET_ADMIN.EMAIL
          valueFrom:
            secretKeyRef:
              name: admin
              key: email
        - name: ROCKET_ADMIN.PASSWORD
          valueFrom:
            secretKeyRef:
              name: admin
              key: password
        - name: ROCKET_DATABASES.ORDERS.URL
          valueFrom:
            secretKeyRef:
              name: redis
              key: uri
        - name: ROCKET_DATABASES.META.URL
          valueFrom:
            secretKeyRef:
              name: postgresql
              key: uri
        - name: ROCKET_DATABASES.ACCOUNTING.URL
          value: tigerbeetle-headless.tigerbeetle:4242
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - name: config
          mountPath: /etc/config
      volumes:
      - name: config
        configMap:
          name: api-config
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: exchange-api
  namespace: exchange
spec:
  maxReplicas: 9
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: exchange
  targetCPUUtilizationPercentage: 60
