apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchange
  namespace: exchange
spec:
  selector:
    matchLabels:
      app: exchange
  template:
    metadata:
      labels:
        app: exchange
    spec:
      containers:
      - name: exchange
        image: suremarc/mkt-sim-exchange:latest
        securityContext:
          privileged: true
        command: 
        - litefs
        - mount
        - -config
        - /etc/config/litefs.yml
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: ROCKET_CONFIG
          value: /etc/config/Rocket.toml
        - name: ROCKET_ADMIN_EMAIL
          valueFrom:
            secretKeyRef:
              name: admin
              key: email
        - name: ROCKET_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: admin
              key: password
        - name: ROCKET_DATABASES_ORDERS_URL
          valueFrom:
            secretKeyRef:
              name: redis
              key: uri
        - name: ROCKET_DATABASES_META_URL
          value: /litefs/my.db
        # todo: figure out how to link tigerbeetle
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - name: config
          mountPath: /etc/config
        - name: litefs
          mountPath: /var/lib/litefs
      volumes:
      - name: config
        configMap:
          name: api-config
      - name: litefs
        persistentVolumeClaim: 
          claimName: litefs-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: litefs-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
