apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchange
  namespace: exchange
spec:
  selector:
    matchLabels:
      app: exchange
  template:
    metadata:
      labels:
        app: exchange
    spec:
      containers:
      - name: exchange
        image: suremarc/mkt-sim-exchange:latest
        command: 
        - litefs
        - mount
        - -config
        - /etc/config/litefs.yml
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: ROCKET_CONFIG
          value: /etc/config/Rocket.toml
        - name: ROCKET_ADMIN_EMAIL
          valueFrom:
            secretKeyRef:
              name: admin
              key: email
        - name: ROCKET_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: admin
              key: password
        - name: ROCKET_DATABASES_ORDERS_URL
          valueFrom:
            secretKeyRef:
              name: redis
              key: uri
        - name: ROCKET_DATABASES_META_URL
          value: data.db
        # todo: figure out how to link tigerbeetle
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - name: config
          mountPath: /etc/config
      volumes:
      - name: config
        configMap:
          name: api-config
