services:
  tigerbeetle:
    image: ghcr.io/tigerbeetle/tigerbeetle
    network_mode: service:exchange
    volumes: [ tigerbeetle:/data ]
    command: start --addresses=127.0.0.1:3000 /data/0_0.tigerbeetle
    depends_on:
      tigerbeetle-format:
        condition: service_completed_successfully
      exchange:
        condition: service_started

  tigerbeetle-format:
    image: ghcr.io/tigerbeetle/tigerbeetle
    volumes: [ tigerbeetle:/data ]
    entrypoint: /bin/sh
    command:
      - -c
      - |-
        if [ ! -f /data/0_0.tigerbeetle ]; then
          ./tigerbeetle format --cluster=0 --replica=0 --replica-count=1 /data/0_0.tigerbeetle
        fi

  exchange:
    image: suremarc/mkt-sim-exchange
    ports: [ 127.0.0.1:8000:8000 ]
    environment:
      - ROCKET_ADDRESS=0.0.0.0
    volumes:
      - type: bind
        source: ./data.db
        target: /opt/exchange/data.db
      - type: bind
        source: ./Rocket.toml
        target: /opt/exchange/Rocket.toml

volumes:
  tigerbeetle:
    driver: local
