VERSION --try 0.8
IMPORT github.com/earthly/lib/rust:2.2.11 AS rust

FROM rust:1.78-bookworm

setup:
    RUN apt-get -y update && apt-get -y install clang mold

    # Install zig
    ARG ZIG_VERS=0.12.0
    COPY +get-zig/zig-linux-x86_64-$ZIG_VERS /usr/local/zig-linux-x86_64-$ZIG_VERS
    ENV PATH=/usr/local/zig-linux-x86_64-$ZIG_VERS:$PATH
    RUN zig version

    # Setup rust environment
    ENV RUSTFLAGS="-C linker=clang -C link-arg=-fuse-ld=/usr/bin/mold"
    DO rust+INIT --keep-fingerprints=true
    RUN rustup component add clippy rustfmt

get-zig:
    RUN curl -LO https://ziglang.org/download/0.12.0/zig-linux-x86_64-0.12.0.tar.xz
    RUN tar xf zig-linux-x86_64-0.12.0.tar.xz
    SAVE ARTIFACT zig-linux-x86_64-0.12.0

copy-src:
    FROM +setup
    WORKDIR /tmp/atlas
    COPY --keep-ts --dir Cargo.toml Cargo.lock src ./

build-debug:
    FROM +copy-src
    DO rust+CARGO --args="build" --output="debug/[^/]+"
    SAVE ARTIFACT target/debug /debug

build-release:
    FROM +copy-src
    DO rust+CARGO --args="build --release" --output="release/[^/]+"
    SAVE ARTIFACT target/release /release

test:
    FROM +copy-src
    DO rust+CARGO --args="test"

fmt:
    FROM +copy-src
    DO rust+CARGO --args "fmt --check"

lint:
    FROM +copy-src
    DO rust+CARGO --args="clippy --all-targets --all-features -- -D warnings"
