[debug.admin]
email = "admin@mkt-sim.com"
password = "password"

[debug.databases]
meta = { url = "data.db" }
accounting = { url = "127.0.0.1:3000" }

[debug.jwt]
token = "b76aed65657602cbc44f26284ef076d9f0a548ef547282ff0500338a60a5bfac"
