name: CI/CD
on: 
  push:
    branches: [ master ]

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  exchange:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: exchange
    strategy:
      fail-fast: false
      matrix:
        target: [fmt, lint, test]
    steps:
    - uses: earthly/actions-setup@v1
      with: 
        version: v0.8.10
    - uses: actions/checkout@v4
    - name: Run +${{ matrix.target }}
      run: earthly --ci +${{ matrix.target }}

  exchange-docker:
    runs-on: self-hosted
    needs: [ exchange ]
    defaults:
      run:
        working-directory: exchange
    steps:
    - uses: earthly/actions-setup@v1
      with: 
        version: v0.8.10
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      run: earthly --push +docker --TARGET=release

  deploy:
    runs-on: ubuntu-22.04
    environment: development
    needs: [ exchange-docker ]
    steps:
    - uses: actions/checkout@v4
    - name: DigitalOcean Kubernetes
      uses: matootie/dokube@v1.4.1
      with:
        personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN }}
        clusterName: mkt-sim
        version: "1.30.1"
    - name: Deploy TigerBeetle
      run: kubectl apply --server-side --force-conflicts --field-manager gh-actions -f k8s/tigerbeetle
    - name: Create Exchange Config
      run: >-
        kubectl -n exchange create configmap exchange-config
          --from-file=Rocket.toml=exchange/Rocket.toml
          --from-file=litefs.yml=exchange/litefs.yml 
          --dry-run=client -o yaml |
          kubectl apply -f -
          --server-side
          --force-conflicts
          --field-manager gh-actions
    - name: Use GH hash
      uses: fjogeleit/yaml-update-action@v0.9.0
      with:
        valueFile: k8s/exchange/deployment.yml
        propertyPath: spec.template.spec.containers[0].image
        value: ${{ github.sha }}
        commitChange: false
    - name: Deploy Exchange
      run: kubectl apply --server-side --force-conflicts --field-manager gh-actions -f k8s/exchange
