name: CICD
on: 
  push:
    branches: [ master ]

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  exchange:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: exchange
    strategy:
      fail-fast: false
      matrix:
        target: [fmt, lint, test]
    steps:
    - uses: earthly/actions-setup@v1
      with: 
        version: v0.8.10
    - uses: actions/checkout@v4
    - name: Run +${{ matrix.target }}
      run: earthly --ci +${{ matrix.target }}

  exchange-docker:
    runs-on: self-hosted
    needs: [ exchange ]
    steps:
    - uses: earthly/actions-setup@v1
      with: 
        version: v0.8.10
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      run: earthly --push +docker --TARGET=release
